### ISSUE TITLE
I need to run only one module tests

### ISSUE THREAD

**Issue by svycka** [prolic/HumusPHPUnitModule#4]
Is it possble to run only one module tests? best solution would be specify  througt comand line also would be nice feature if I could use all phpunit options because this module ignores all command line arguments

**Comment by prolic** [comment]
You can specify in the phpunit.xml file which options you like for a given module / library incl. creating a white- / or blacklist. Ain't that sufficient?

**Comment by svycka** [comment]
I am more thinking about:
humusphpunit -m firstmodule
humusphpunit -m firstmodule,second
humusphpunit -all

and sometimes I need something like `--filter` from phpunit thats not like I always want this to be in my `phpunit.xml`

**Comment by prolic** [comment]
Something like:

```
humusphpunit -m firstmodule
humusphpunit -m firstmodule,second
humusphpunit -all
```

is possible without problems. But with the --filter option it is, because it's unknown to which module the filter option belongs.

**Comment by svycka** [comment]
If it is possible any example? also if I understand correctly you run phpunit command for every module why cant you just copy all comand line arguments to phpunit? thats not only --filter maybe sometimes I need --verbose or anything else I would love to have a way to pass it throuht

**Comment by prolic** [comment]
Scenario 2 Modules: 
ModuleOne and ModuleTwo

humusphpunit --filter tests/MyTestCase.php

Problem: There is no tests/MyTestCase.php in ModuleOne, only in ModuleTwo.

What we can do, is pass the parameters like --debug oder --strict, but with group and filter f.e. I see problems, because you want to assign those parameters to a specific module instead.

Additional comment:
It is not that useful, to have something link:

```
humusphpunit --m ModuleOne --filter tests/MyTestCase.php --debug
```

Because it's the same as

```
phpunit --m ModuleOne --filter tests/MyTestCase.php --debug
```

So there is no real reason, why I would want to use humusphpunit instead of phpunit.

**Comment by svycka** [comment]
Hmm, so your suggestion would be not use humusphpunit  if I need --debug sometimes and use phpunit instead?? I can't see BC break here just additional feature can't see why its bad?

**Comment by prolic** [comment]
The only thing I am trying to say, is that not all parameters that are usefull for phpunit are useful für humusphpunit. f.e. "--filter", and perhabs even "--group", but I not sure about the last one.

Agree with adding -m module switches and --debug and --strict options.

**Comment by svycka** [comment]
ok maybe you are right.
